# Generated by Django 4.2.7 on 2023-12-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_rename_name_project_title_remove_issue_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_issues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
