# Generated by Django 4.2.7 on 2023-12-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_contributor_user_contributor_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_author',
        ),
    ]
